_wandb:
    value:
        cli_version: 0.23.0
        e:
            fmqvi28h5x8gubk3phwlki40ndpxldd2:
                args:
                    - --devices
                    - "1"
                    - --config
                    - config_coronary_debug
                codePath: repairing/near_repairing/stage1_coronary/train_coronary_pl.py
                codePathLocal: train_coronary_pl.py
                cpu_count: 40
                cpu_count_logical: 40
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "67108864"
                        used: "12288"
                email: c15919822199@gmail.com
                executable: /projappl/project_2016517/chengjun/junjieenv/bin/python
                git:
                    commit: 2300d3e37087a9655f63733c27fe6544be0dcfc5
                    remote: https://github.com/Junjiecheng2024/NeAR_fix_Public-Cardiac-CT-Dataset
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-1b5752ff-7287-4201-9f01-20e4911978e2
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-56cc155d-7394-8e72-852f-77abc4b54d50
                host: r17g04.bullx
                memory:
                    total: "403794300928"
                os: Linux-4.18.0-553.74.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /projappl/project_2016517/chengjun/NeAR_fix_Public-Cardiac-CT-Dataset/repairing/near_repairing/stage1_coronary/train_coronary_pl.py
                python: CPython 3.10.14
                root: .
                slurm:
                    cluster_name: puhti
                    conf: /etc/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000200000
                    cpu_bind_list: "0x0000200000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "1"
                    cpus_per_task: "1"
                    distribution: cyclic
                    gpus_on_node: "2"
                    gtids: "0"
                    job_account: project_2016517
                    job_cpus_per_node: "1"
                    job_end_time: "1763450813"
                    job_gid: "10033029"
                    job_group: pepr_chengjun
                    job_id: "30584429"
                    job_name: interactive
                    job_nodelist: r17g04
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1763443613"
                    job_uid: "10033029"
                    job_user: chengjun
                    jobid: "30584429"
                    launch_node_ipaddr: 10.140.14.60
                    localid: "0"
                    mem_per_node: "65536"
                    mpi_type: pmix_v3
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: r17g04
                    nprocs: "1"
                    ntasks: "1"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "34007"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "45137"
                    pty_win_col: "111"
                    pty_win_row: "20"
                    script_context: prolog_task
                    srun_comm_host: 10.140.14.60
                    srun_comm_port: "39127"
                    step_gpus: 1,3
                    step_id: "0"
                    step_launcher_port: "39127"
                    step_nodelist: r17g04
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 13523-13524
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /users/chengjun
                    submit_host: puhti-login11.bullx
                    task_pid: "2762038"
                    tasks_per_node: "1"
                    threads_per_core: "1"
                    topology_addr: r17g04
                    topology_addr_pattern: node
                    tres_per_task: cpu=1
                    umask: "0007"
                startedAt: "2025-11-18T06:50:12.515364Z"
                writerId: fmqvi28h5x8gubk3phwlki40ndpxldd2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.10.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
decoder_channels:
    value:
        - 64
        - 48
        - 32
        - 16
dice_weight:
    value: 0.7
focal_alpha:
    value: 0.25
focal_gamma:
    value: 4
focal_weight:
    value: 0.3
gamma:
    value: 0.5
l2_penalty_weight:
    value: 0.0001
latent_dimension:
    value: 256
lr:
    value: 0.001
milestones:
    value:
        - 100
        - 200
n_samples:
    value: 998
total_steps:
    value: null
use_cosine_schedule:
    value: false
warmup_ratio:
    value: 0.01
